import Head from 'next/head'
import Sidebar from '../components/Sidebar'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Daniel's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Sidebar */}
      <Sidebar />
      {/* Hero */}
      {/* About */}
      {/* Skills */}
      {/* Projects */}
      {/* Contact Me */}
    </div>
  )
}
