import Head from 'next/head'
import About from '../components/About'
import Hero from '../components/Hero'
import Sidebar from '../components/Sidebar'



export default function Home() {
  return (
    <div className="-z-50">
      <Head>
        <title>Daniel's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Sidebar */}
      <Sidebar />
      {/* Hero */}
      <Hero />
      {/* About */}
      <About />
      {/* Skills */}
      {/* Projects */}
      {/* Contact Me */}
    </div>
  )
}
